### PR TITLE
✨ Add footer and container components

### LINKED ISSUE #17: Footer Component
Please refer to the design: https://xd.adobe.com/spec/967e129d-f3bb-4a08-6f39-553da7ddef6d-e04f/

### PR DESCRIPTION
**Pull request by psongpin**
**Description**
- This PR includes the footer component for the homepage

**Summary of Changes**
- Added container component
- Added footer component
- Added react-fontawesome

**Screenshots**
Screen Shot 2019-09-29 at 1 09 28 AM

Closes #17

### CODE REVIEW

**Comment by franreysaycon** [comment]
Huge question: I have no problem whatever is the answer to this. 
Do we promote the use of render props or any component based approach with sharing data such as <StaticQuery> or we use hooks moving forward? useStaticQuery()?

I like the idea of being consistent.

**Comment by RemLampa** [comment]
+1 to consistency (with rare unforeseen exceptions). :D The dev team may choose among themselves which pattern to follow.

**Comment by psongpin** [comment]
Did not know there was a hook api for gatsby. Not until you all mentioned it I will modify this later.

**Comment by RemLampa** [comment]
Haha. Ang mindset na ata ngayon ay "is there a hook for this"?

:heart: hooks :heart:

**Comment by psongpin** [comment]
Issue with hooks is fixed. just need the assets from the designer.

**Comment by psongpin** [comment]
Screen Shot 2019-09-29 at 12 17 52 AM

Sorry for the late continuation. This is the initial footer component. I changed the social icons with FontAwesome Icons for consistency. Requesting for review thanks guys!

**Pull request merged**
