### PR TITLE
Add missing prop-types

### PR DESCRIPTION
**Pull request by franreysaycon**
Just adding a missing prop type declaration as went through the codebase.
This should be on top of github-pages-deploy #24.

### CODE REVIEW

**Comment by jromest** [comment]
PropType linter has been [disable](https://github.com/reactph/reactjsph-website/blob/1ccff4aaa5242bbc7b53fe50c61df421b97ee4ee/.eslintrc#L17), kaya walang linting error

**Comment by franreysaycon** [comment]
Should that be disabled though?

**Comment by jromest** [comment]
I'm not sure 😅

**Comment by franreysaycon** [comment]
@jromest shouldn't be a big deal. we can just let it slide for now. let's just cover everything with prop types as much as we can as we are not using any type strictness.

**Pull request merged**
