### PR TITLE
feat: ✨ working netlify forms with recaptcha

### PR DESCRIPTION
**Pull request by itsdyeyson**
**Description**
Integrate Netlify forms

**Summary of Changes**
- Add .env.development in .gitignore
- Add additional packages to make work the recaptcha, form handling.
- Update the contact.js to integrate the netlify form.
- Add portal.js to have successful message modal.

**How to Test**
- For local testing, please create a .env.development file and the following fields:

```
GATSBY_SITE_RECAPTCHA_KEY=<YOUR-SITE_RECAPTCHA-KEY>
GATSBY_SITE_RECAPTCHA_SECRET=<YOUR-SITE_RECAPTCHA-SECRET>
```
To generate a recaptcha keys and secrets:
1. Go to https://www.google.com/u/3/recaptcha/admin/create.
2. Fill up the required fields. Note: Select Recaptcha V2 - Invisible recaptcha badge.
3. Submit and copy the key and secret code.

NOTE: It won't work on deploy preview.

**Screenshots**
With Input Validation
image

Message Success
image

### CODE REVIEW

**Comment by itsdyeyson** [comment]
@jromest  what browser are you using? In Google Chrome, it works fine.

Screen Shot 2020-03-10 at 10 50 35 AM

Screen Shot 2020-03-10 at 10 50 42 AM

**Comment by jromest** [comment]
> @jromest what browser are you using? In Google Chrome, it works fine.

@itsdyeyson Firefox, I checked it on Chrome, and yes, it works fine.

**Comment by itsdyeyson** [comment]
@jromest 

Text are font updated.
Screen Shot 2020-03-13 at 4 09 05 PM

Close Icon is working in Mozilla. No changes made.
Screen Shot 2020-03-13 at 4 09 13 PM

**Comment by jromest** [comment]
> Close Icon is working in Mozilla. No changes made.

I mean, if it would be better to put the word `close` instead of `x`? What do you think?

**Comment by itsdyeyson** [comment]
I think. The user will get when we use x icon.

**Pull request merged**
