### PR TITLE
Randomize Dev Board

### PR DESCRIPTION
**Pull request by oliverJurgen**
Anytime a randomized dev list is needed again.
For Hacktoberfest :P

### CODE REVIEW

**Comment by franreysaycon** [comment]
hey oliver! I think there's a problem with shuffling the images that's why we turned it off for now. did you happen to cross that? haha.

**Comment by oliverJurgen** [comment]
Ill ask @codekcv about that. 

Yo man, what was the issue being caused by shuffling of the dev list?
Was it this one? 
image

tested on my side, not happening.

**Comment by codekcv** [comment]
> Ill ask @codekcv about that.
> 
> Yo man, what was the issue being caused by shuffling of the dev list?
> Was it this one?
> image
> 
> tested on my side, not happening.

Yeah man, it's not happening locally, but when 

> Ill ask @codekcv about that.
> 
> Yo man, what was the issue being caused by shuffling of the dev list?
> Was it this one?
> image
> 
> tested on my side, not happening.

Yo Oliver. Yep yep it works locally, but once the build version with gatsby stuff, the image shuffle bug occurs.
Try this, update the shuffle util so it doesn't mutate the array. Gatsby doesn't like mutating objects.
Make it create another array and shuffle that and return that one instead.

**Comment by oliverJurgen** [comment]
I see thanks, will work on this in a while

**Comment by jisundr** [comment]
I fixed the merge conflict. Did I just merged this to master?

**Comment by jromest** [comment]
> I fixed the merge conflict. Did I just merged this to master?

@jisundr No, you just merged the master branch to this PR's branch.

**Pull request closed without merging**
